In [26]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import Input

In [16]:
reviews = [
    "nice food",
    "amazing restaurant",
    "too good",
    "just loved it!",
    "will go again",
    "horrible food",
    "never go there",
    "poor service",
    "poor quality",
    "needs improvement",
    "amazing food",
    "poor food",
    "poor restaurant",
    "loved food",
    "good food",
]

sentiment = np.array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1])

In [17]:
one_hot("amazing restaurant",30)

[5, 21]

In [18]:
vocab_size = 30
encoded_reviews = [one_hot(review, vocab_size) for review in reviews]
encoded_reviews

[[9, 10],
 [5, 21],
 [4, 7],
 [24, 19, 13],
 [28, 16, 7],
 [17, 10],
 [3, 16, 27],
 [14, 15],
 [14, 16],
 [25, 27],
 [5, 10],
 [14, 10],
 [14, 21],
 [19, 10],
 [7, 10]]

In [19]:
# to pad the sentences to make same length
max_length = 3
padded_reviews = pad_sequences(encoded_reviews, 
                               maxlen=max_length, 
                               padding="post")
padded_reviews

array([[ 9, 10,  0],
       [ 5, 21,  0],
       [ 4,  7,  0],
       [24, 19, 13],
       [28, 16,  7],
       [17, 10,  0],
       [ 3, 16, 27],
       [14, 15,  0],
       [14, 16,  0],
       [25, 27,  0],
       [ 5, 10,  0],
       [14, 10,  0],
       [14, 21,  0],
       [19, 10,  0],
       [ 7, 10,  0]])

In [39]:
embedding_vector_size = 5
model = Sequential(
    [
        # Input(shape=(15, 3)),
        Embedding(
            vocab_size, embedding_vector_size, input_length=max_length, name="embedding"
        ),
        Flatten(),
        Dense(1, activation="sigmoid"),
    ]
)

In [40]:
X = padded_reviews
y = sentiment

In [41]:
model.compile(optimizer="adam", 
              loss="binary_crossentropy", 
              metrics=["accuracy"])

model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_5 (Flatten)             │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [42]:
model.fit(X, y, epochs=50, verbose = False)

In [43]:
loss, accuracy = model.evaluate(X,y)
accuracy

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 248ms/step - accuracy: 1.0000 - loss: 0.6165


1.0

In [48]:
weights = model.get_layer("embedding").get_weights()[0]

In [49]:
len(weights)

30

In [52]:
weights[9]

array([-0.01012843,  0.09294356,  0.00144134, -0.02197852, -0.00151562],
      dtype=float32)

In [53]:
weights[5]

array([-0.0524598 ,  0.05172729,  0.03163588, -0.05267007, -0.10754716],
      dtype=float32)

#### nice and amazing are looking similar 

#### In this session, i learnt about word embedding